### ISSUE TITLE
Menu item function parameters

### ISSUE THREAD

**Issue by rgrossman3DMed** [pololu/pololu-menu-arduino#1]
Is there a way to make the menu items' functions have parameters? 
So instead of:
static const PololuMenuItem items[] = {
    { F("Item one"), myFunction1 },
    { F("Item two"), myFunction2 },
  };

you can do:
static const PololuMenuItem items[] = {
    { F("Item one"), myFunction(1) },
    { F("Item two"), myFunction(2) },
  };

Thank you for any updates

**Comment by pdg137** [comment]
The library doesn't allow functions with parameters in those spots so it's really a question of how to do this kind of thing in C++. You can try using lambda functions:
```cpp
static const PololuMenuItem items[] = {
  { F("Item one"), [](){ myFunction(1); } },
  { F("Item two"), [](){ myFunction(2); } },
};
```
Or, if that doesn't work, make intermediate functions:
```cpp
void myFunction1() { myFunction(1); }
void myFunction2() { myFunction(2); }
```
